import {  B612_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "../components/NavBar";
import Footer from "../components/Footer";

 


const b612 = B612_Mono({
  variable: "--font-b612-mono",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata = {
  title: "Attirmidzi's Portfolio",
  keywords: ["Attirmidzi", "Portfolio", "Web Development", "Public Speaking"],
  description: "Generated by create next app",
  
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={` ${b612.variable} antialiased`}
      >
        <Navbar />
        
        {children}
        <Footer />
      </body>
    </html>
  );
}

